"""empty message

Revision ID: 274faae5d6c2
Revises: 
Create Date: 2023-04-15 15:16:21.790661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274faae5d6c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('email', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'email')
    # ### end Alembic commands ###
