"""empty message

Revision ID: a37ebeb938cc
Revises: 274faae5d6c2
Create Date: 2023-04-17 11:27:50.703110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37ebeb938cc'
down_revision = '274faae5d6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('doctors', sa.Column('password', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'doctors', ['username'])
    op.create_unique_constraint(None, 'patients', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'password')
    op.drop_column('doctors', 'username')
    # ### end Alembic commands ###
